image: golang:1.23.6

stages:
  - format
  - lint
  - build

format:
  timeout: 5min
  stage: format
  script:
    - make fmt

lint:
  timeout: 7min
  stage: lint
  script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.5
    - go install honnef.co/go/tools/cmd/staticcheck@latest
    - make vet
    - make lint
    - make staticcheck

build:
  stage: build
  script:
    - mkdir -p bin
    - make build-linux
    - make build-windows
    - make build-macos
  artifacts:
    paths:
      - bin/checker
      - bin/checker.exe
